// Because PersonDetails is generated and regenerated by the Core Data model, we'll keep its methods here.

#import <Foundation/Foundation.h>
#import "PersonDetails.h"

@interface PersonDetails (Methods)

+ (PersonDetails *)retrieveOrCreate:(NSDictionary *)selectedResult;
+ (id)realValueFromPersonDetailsJSONDict:(NSDictionary *)jsonDict forKey:(NSString *)key;
+ (NSString *)joinedValueFromPersonDetailsJSONDict:(NSDictionary *)jsonDict forKey:(NSString *)key;

@end
